### ISSUE TITLE
Allow connecting the car to the app

### ISSUE THREAD

**Issue by Lancear** [DIT113-V22/group-01#13]
As a user, I want to be able to connect my car to the app so that I can easily monitor the car's sensor data.

<br>

**Acceptance Criteria:**
- [x] Given I am a user when I try to connect a car to the app then the system informs me the car’s status.
- [x] I want to be able to check the status of the car
- [x] The connection to the car is made using the java sdk
- [x] ~~Multiple cars can be connected~~
- [x] All connected cars are visible in the app
- [x] The implementation is tested manually

**Subtasks:**
- [x] Create a topic which sends the current time (car) @Lancear 
- [x] Create a screen for connecting to the car manually @Lancear 
- [x] Display steps for setting everything up for connection @GeorgZs 
- [x] When the car is connected the screen changes as follows:
  - [x] Connection button becomes a disconnect button @Lancear 
  - [x] Steps to set up connection get replace with the cars status info:
    - [x] Connected / Connection Lost badge @bardiaForooraghi 
    - [x] Last update received timestamp @bardiaForooraghi 
    - [x] Clicking on this car card brings you to the sensors and manual driving @GeorgZs 
- [x] Store the connected car in a singleton state class @Lancear
